development:
  adapter: mysql
  encoding: utf8
  database: elo_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  encoding: utf8
  database: elo_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  encoding: utf8
  database: rails
  pool: 5
  username: rails
  password: MKv6QJyEAv
  socket: /var/run/mysqld/mysqld.sock

mock_production:
  adapter: mysql
  encoding: utf8
  database: elo_production
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock