development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: mmehlhope
  :password: secksi02
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: mmehlhope
  :password: secksi02
  :enable_starttls_auto: true