optimize: none
modules:
  - name: application
paths:
  text: 'requirejs-text'
  views: 'backbone/views'
  jquery: 'jquery-1.11.1.min'
  globals: 'globals'

shim:
  requirejs: [hamlcoffee, text]
  bootstrap: [jquery]
